### ISSUE TITLE
Question - Expected behaviour of toSnakeCase

### ISSUE THREAD

**Issue by gcmartins93** [travelperk/case-converter#27]
Hi,

Just a little question. What shout be the expected behavior of `toSnakeCase()` when applied to an object with an `address1` key?

I've got `address_1`, and frameworks like rails expect `address1`, so I've search through your source code and figured out that you are using loadsh for string/key parsing, and couldn't figure out how to send `_.snakeCase` a new pattern and then make possible to customize `toSnakeCase` calls to work according to user needs. Any idea instead of requesting a loadash pull request to add this feature?

**Comment by MoeSattler** [comment]
Hi @gcmartins93,

interesting question. Not sure.
Can you open a PR with a (failing) test case for this scenario so we can check it out?
