### ISSUE TITLE
Date Object disappears after case-converter use

### ISSUE THREAD

**Issue by DeadEye0112** [travelperk/case-converter#9]
Hi,

I'm facing a problem where dates keys converted through case-converter seems to be emptied.
Here, `user` is an object returned from my ORM. That's why `attributes` level is removed after toJSON() call.
```
> user.attributes.created_at
2016-08-17T09:56:04.236Z
  __proto__:Date
> user.toJSON().created_at
2016-08-17T09:56:04.236Z
  __proto__:Date
> caseConverter.toSnakeCase(user.toJSON()).created_at
Object
  __proto__:Object
```
toCamelCase have the same behavior (except the key is name createdAt, of course...).
Is this a bug or am I missing something ?

Thanks !

**Comment by Gpx** [comment]
Hi @DeadEye0112 I'll try to take a look at it this evening

**Comment by DeadEye0112** [comment]
Hey ! Thanks ! :D

**Comment by Gpx** [comment]
I run this small test

```js
const date = new Date()
const converted = toSnakeCase(date)
date instanceof Date // true
converted instanceof Date // false
```

What's probably happening is that `toSnakeCase` is messing up with `Date`'s prototype and as a result, we get back a corrupted `Date` object.

I think `case-converter` should leave alone native objects methods, but I would like to hear @Moezalez's input on this one.

**Comment by Moezalez** [comment]
@Gpx Yes, I suppose so.

Ideally case-converter should just convert two type of objects:
- Arrays
- "Key-Value objects"

Not sure how to check for that. Any idea?

**Comment by DeadEye0112** [comment]
I confirm your statement @Gpx. From what I see, `case-converter` copy only keys and values. The problem with `Date` Object is that it contains no keys but the Object still have a value.

**Comment by Gpx** [comment]
What about adding a simple check `if (obj instanceof Date)` we don't convert it?

**Comment by DeadEye0112** [comment]
That would fix the problem for `Date`'s prototypes but are we sure that there are no other prototypes with a similar behavior ? (`Error` prototype has probably the same behavior)

**Comment by Moezalez** [comment]
This is my worry, too. 
For now I propose that we just check for enumerable properties, as in my PR:
https://github.com/travelperk/case-converter/pull/10

**Comment by Moezalez** [comment]
@DeadEye0112 update to 1.0.1 and you should be fine. If you run into any issues, let us know.
